spring:
  mvc:
    static-path-pattern: /view/**
  kafka:
    bootstrap-servers: localhost:9092
    group-id: recipetory-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/recipetory?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PW}
  data:
    elasticsearch:
      hosts: localhost
      port: 9200
  redis:
    host: localhost
    port: 6379
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
#        show_sql: true
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434863591116-p6q49kru7143ns8sijumbtt9m9aqjghf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-name: naver
            client-id: _YViRKOdxMmGRU0ce1Od
            client-secret: G7U5VZrLnL
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email,nickname
          kakao:
            client-name: kakao
            client-id: 723a0fcadd538ef48944c04f5b32e8a6
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id