spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.178.0.3:3306/recipetory?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${MYSQL_PW}
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 434863591116-p6q49kru7143ns8sijumbtt9m9aqjghf.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          naver:
            client-name: naver
            client-id: xCOoChU6Z_Y0mqFWAigP
            client-secret: wTKSqsL3gH
            redirect-uri: http://34.64.192.158/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email,nickname
          kakao:
            client-name: kakao
            client-id: 440b9d834501c4337ae0d9c753156417
            redirect-uri: http://34.64.192.158/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: account_email,profile_nickname
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id